# Generated by Django 4.1.4 on 2023-03-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Health_facility', models.CharField(max_length=200)),
                ('worker_health_name', models.CharField(max_length=150)),
                ('patient_name', models.CharField(max_length=150)),
                ('patient_ID', models.CharField(max_length=50)),
                ('Date_of_birth', models.DateField(blank=True, null=True)),
                ('Country', models.CharField(max_length=100)),
                ('Region', models.CharField(choices=[('Adamaoua', 'Adamaoua'), ('Centre', 'Centre'), ('Est', 'Est'), ('Extrême Nord', 'Extrême Nord'), ('Littoral', 'Litoral'), ('Nord', 'Nord'), ('Nord Ouest', 'Nord ouest'), ('Ouest', 'Ouest'), ('Sud', 'Sud'), ('Sud Ouest', 'Sud Ouest')], max_length=20, null=True)),
                ('District', models.CharField(choices=[('Bankim', 'Bankim'), ('Banyo', 'Banyo'), ('Dang', 'Dang'), ('Tibati', 'Tibati'), ('Ngaoundere Rural', 'Ngaoundere Rural')], max_length=40, null=True)),
                ('sexe', models.CharField(choices=[('masculin', 'Male'), ('feminin', 'Female')], max_length=8, null=True)),
                ('Village', models.CharField(max_length=150)),
                ('Phone_number', models.CharField(blank=True, max_length=12)),
                ('Occupation', models.CharField(max_length=150)),
                ('Landmark', models.CharField(max_length=150)),
                ('Contact_person', models.CharField(max_length=250)),
                ('Contact_person_phone', models.CharField(blank=True, max_length=12)),
                ('detection_mode', models.CharField(choices=[('Active screening', 'Active screening'), ('School survey', 'School survey '), ('Referred', 'Referred'), ('Passive', 'Passive'), ('Other', 'Other')], max_length=100)),
                ('classification', models.CharField(choices=[('New', 'New'), ('Recurrent', 'Recurent')], max_length=100)),
                ('duration_illnes', models.PositiveIntegerField()),
                ('use_traditional', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100)),
                ('any_treat', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('treat_prev', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('Referred_by', models.CharField(choices=[('self-referral', 'self-referral'), ('Health worker', 'Health worker'), ('Village', 'Village'), ('Traditional healer', 'Traditional healer'), ('Family member', 'Family member'), ('Former patient', 'Former patient'), ('School Teacher', 'School Teacher'), ('Other', 'Other')], max_length=30, null=True)),
                ('Family_member', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('other_mode_detection', models.CharField(blank=True, max_length=200, null=True)),
                ('specify_any_treatment', models.CharField(blank=True, max_length=200, null=True)),
                ('duration_any', models.CharField(blank=True, max_length=200, null=True)),
                ('specify_for_previous', models.CharField(blank=True, max_length=200, null=True)),
                ('duration_for_previous', models.CharField(blank=True, max_length=200, null=True)),
                ('number_family_close', models.CharField(blank=True, max_length=200, null=True)),
                ('TB_status', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unknown', 'Unknown')], max_length=30)),
                ('limitation_mov', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('limitation_daily_act', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('date_enregistrement', models.DateField(blank=True, null=True)),
                ('relationship', models.CharField(blank=True, max_length=150, null=True)),
                ('weigth', models.CharField(max_length=150)),
                ('pregnant', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], max_length=30)),
                ('HIV_status', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unknown', 'Unknown')], max_length=30)),
                ('diagnosis', models.CharField(blank=True, max_length=150, null=True)),
                ('other_referred', models.CharField(blank=True, max_length=150, null=True)),
                ('category_lesion', models.CharField(choices=[('Category I', 'Category I'), ('Category II', 'Category II'), ('Category III', 'Category III')], max_length=50)),
                ('no_lesions', models.CharField(blank=True, max_length=4, null=True)),
                ('diameter', models.CharField(blank=True, max_length=10, null=True)),
                ('Clinical_form', models.CharField(blank=True, max_length=250, null=True)),
                ('Location_lesion', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
